name: Scrape Leaderboard

on: [push, workflow_dispatch]
 # schedule:
  #  - cron: '00 00 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run script
      run: python ./scrape_trending_chat.py

    - name: Commit and push if it's not a fork
      #if: github.event_name == 'schedule' && github.repository == github.event.repository.full_name
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git stash
        git pull --rebase
        git stash pop
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
